name    'puppetlabs-debbuilder'
version '0.0.1'
source 'git@github.com:haus/debbuilder.git'
author 'puppetlabs'
license 'Puppet Enterprise Software License Agreement'
summary 'Debian package builder'
description 'Module to set up a debian builder'
project_page 'https://github.com/haus/debbuilder.git'
